version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: IdeaHub-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: startup-buddy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - IdeaHub-network

  # Redis for BullMQ
  redis:
    image: redis:7-alpine
    container_name: IdeaHub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - IdeaHub-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: IdeaHub-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/startup-buddy?authSource=admin
      REDIS_URL: redis://redis:6379
      CEREBRAS_API_KEY: ${CEREBRAS_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    networks:
      - IdeaHub-network
    volumes:
      - ./backend/uploads:/app/uploads

  # Worker for background jobs
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: IdeaHub-worker
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/startup-buddy?authSource=admin
      REDIS_URL: redis://redis:6379
      CEREBRAS_API_KEY: ${CEREBRAS_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    depends_on:
      - mongodb
      - redis
      - backend
    networks:
      - IdeaHub-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: IdeaHub-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - IdeaHub-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: IdeaHub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - IdeaHub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  IdeaHub-network:
    driver: bridge