api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"

# Define middleware for headers, redirects, etc
http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: false
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    compress:
      compress: {}

  # Define routing rules
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      middlewares:
        - security-headers
        - compress
      entrypoints:
        - web

    backend:
      rule: "PathPrefix(`/api`)"
      service: backend
      middlewares:
        - security-headers
        - compress
      entrypoints:
        - web

    vectordb:
      rule: "PathPrefix(`/vectordb`)"
      service: vectordb
      middlewares:
        - security-headers
        - compress
      entrypoints:
        - web

  # Define services and backend servers
  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    vectordb:
      loadBalancer:
        servers:
          - url: "http://vectordb:8000"
